/**
 * Assemble `client/client.js` — the browser bundle the DSH client-module system
 * serves for this package.
 *
 * The host serves exactly one file per plugin (`exports["./client"]`), so the
 * readable sources under `src/client/` are wrapped into the module-loader
 * envelope here and the binary artwork is inlined as data URLs. Nothing is
 * transformed: the sources are written in CommonJS and run inside the envelope's
 * own registry, which keeps the build dependency-free.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const read = (path) => readFileSync(join(root, path), 'utf8')
const dataUrl = (path, mime) => `data:${mime};base64,${readFileSync(join(root, path)).toString('base64')}`

/** Modules are keyed by their source path so `require('./x.js')` just works. */
const MODULES = [
  ['artwork.js', 'src/client/artwork.js'],
  ['digitile.js', 'src/client/digitile.js'],
  ['styles.js', 'src/client/styles.js'],
  ['hero.js', 'src/client/hero.js'],
  ['index.js', 'src/client/index.js'],
]

const PLACEHOLDERS = [
  ['__DOUBAO_ARTWORK_MARK__', dataUrl('assets/doubao-mark@2x.png', 'image/png')],
  ['__DOUBAO_ARTWORK_CHARACTER__', dataUrl('assets/doubao-character.png', 'image/png')],
  ['__DOUBAO_ARTWORK_WHALE__', dataUrl('assets/deepseek-whale.svg', 'image/svg+xml')],
]

const indent = (text, spaces) =>
  text
    .split('\n')
    .map((line) => (line === '' ? line : ' '.repeat(spaces) + line))
    .join('\n')

const factories = MODULES.map(
  ([id, path]) => `    ${JSON.stringify('./' + id)}: (module, exports, require) => {\n${indent(read(path), 6)}\n    },`,
).join('\n')

const bundle = `/* Generated by tools/build-client.mjs — edit src/client/* and rebuild. */
window.__ModuleLoader__.load({
  id: "dsh-theme-doubao",
  factory: (require) => {
    const __factories = {
${factories}
    };
    const __cache = {};
    /** Resolve this package's own modules, then fall through to the host table. */
    const __load = (id) => {
      if (__factories[id] === undefined) return require(id);
      const cached = __cache[id];
      if (cached !== undefined) return cached.exports;
      const record = { exports: {} };
      __cache[id] = record;
      __factories[id](record, record.exports, __load);
      return record.exports;
    };
    const module = { exports: {} };
    module.exports = __load("./index.js");
    return module.exports;
  }
});
`

/** Inject the artwork without letting a data URL break out of its string literal. */
const withArtwork = (source) => {
  let out = source
  for (const [placeholder, value] of PLACEHOLDERS) {
    const token = `'${placeholder}'`
    if (!out.includes(token)) throw new Error(`build-client: ${placeholder} is not referenced by any source`)
    out = out.split(token).join(JSON.stringify(value))
  }
  return out
}

mkdirSync(join(root, 'client'), { recursive: true })
writeFileSync(join(root, 'client/client.js'), withArtwork(bundle))
const bytes = readFileSync(join(root, 'client/client.js')).length
console.log(`client/client.js written (${(bytes / 1024).toFixed(1)} KiB)`)
